#!/usr/bin/env python3

import distutils.sysconfig
import os
import sys

cmake_install_prefix = os.getenv('CMAKE_INSTALL_PREFIX', '')

sitelib = distutils.sysconfig.get_python_lib(
    prefix=cmake_install_prefix,
    plat_specific=False)

sitearch = distutils.sysconfig.get_python_lib(
    prefix=cmake_install_prefix,
    plat_specific=True)

if __name__ == '__main__':
    argument, = sys.argv[1:]
    if argument in ('sitelib', 'sitearch'):
        print(globals()[argument])
    else:
        print('Unknown argument!', file=sys.stderr)
        sys.exit(1)
