#!/usr/bin/env python3

from sys import argv
from distutils.sysconfig import get_python_lib


if __name__ == '__main__':
    prefix = argv[1]

    paths = set()
    paths.add(get_python_lib(plat_specific=False, prefix=prefix))
    paths.add(get_python_lib(plat_specific=False, prefix=prefix))

    print(';'.join(list(paths)))
