#!/bin/bash
set -eu -o pipefail

LIBQPBO_VERSION=1.4.1
MESON_VERSION=0.64.1

buildtype=debugoptimized
if [[ $# -ge 1 ]]; then
	buildtype="$1"
fi

temp_dir=$(mktemp -d)
trap 'rm -rf "${temp_dir}"' EXIT

source_dir=$(pwd)
prefix="${temp_dir}/install"

pythonlibdir="${prefix}/lib/python/site-packages"

export PKG_CONFIG_PATH="${prefix}/lib/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}"
export LD_LIBRARY_PATH="${prefix}/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
export PYTHONPATH="${pythonlibdir}${PYTHONPATH:+:${PYTHONPATH}}"
export PATH="${prefix}/bin${PATH:+:${PATH}}"

meson_args=(
	--prefix="${prefix}"
	--bindir=bin
	--libdir=lib
	-Db_ndebug=if-release
	-Dbuildtype="${buildtype}"
	-Dc_args='-march=native -mtune=native'
	-Dcpp_args='-march=native -mtune=native'
	-Dpython.platlibdir="${pythonlibdir}"
	-Dpython.purelibdir="${pythonlibdir}"
)

# Uncomment the next line if you want to enable your IDE to pick up the correct
# compile options.
# ln -nsf "${temp_dir}/libmpopt-build/compile_commands.json" compile_commands.json

# Some older Linux distributions (e.g. Ubuntu 22.04) ship an older version of
# meson. We need some newer features (e.g. prefer-static in 0.63). Therefore we
# fetch the latest version and link it into our temporary prefix.
cd "${temp_dir}"
if [[ -f "${source_dir}/.cache/meson-${MESON_VERSION}.tar.gz" ]]; then
	echo "Using cached meson-${MESON_VERSION}.tar.gz asset."
	cp "${source_dir}/.cache/meson-${MESON_VERSION}.tar.gz" .
else
	curl -LO "https://github.com/mesonbuild/meson/releases/download/${MESON_VERSION}/meson-${MESON_VERSION}.tar.gz"
	mkdir -p "${source_dir}/.cache"
	cp "meson-${MESON_VERSION}.tar.gz" "${source_dir}/.cache/"
fi
tar -xf "meson-${MESON_VERSION}.tar.gz"
mkdir -p "${prefix}/bin"
ln -sT "${temp_dir}/meson-${MESON_VERSION}/meson.py" "${prefix}/bin/meson"

# Install pulp to have a non-commercial LP solver available.
python3 -m pip install --target="${pythonlibdir}" pulp

# libqpbo is an optional requirement, but used for various important things.
# Therefore we fetch the latest version and install it into our temporary
# prefix.
cd "${temp_dir}"
if [[ -f "${source_dir}/.cache/libqpbo-${LIBQPBO_VERSION}.tar.gz" ]]; then
	echo "Using cached libqpbo-${LIBQPBO_VERSION}.tar.gz asset."
	cp "${source_dir}/.cache/libqpbo-${LIBQPBO_VERSION}.tar.gz" .
else
	curl -LJO "https://github.com/fgrsnau/libqpbo/archive/v${LIBQPBO_VERSION}.tar.gz"
	mkdir -p "${source_dir}/.cache"
	cp "libqpbo-${LIBQPBO_VERSION}.tar.gz" "${source_dir}/.cache/"
fi
tar -xf "libqpbo-${LIBQPBO_VERSION}.tar.gz"
mkdir libqpbo-build
cd libqpbo-build
meson setup "${meson_args[@]}" "../libqpbo-${LIBQPBO_VERSION}"
ninja install

# Now we can build and install libmpopt into our temporary prefix and
# afterwards run a shell.
cd "${temp_dir}"
mkdir libmpopt-build
cd libmpopt-build
meson setup "${meson_args[@]}" -Dqpbo=enabled -Dgurobi=auto "${source_dir}"
ninja install

${SHELL}
