#!/bin/bash
set -eu -o pipefail

buildtype=debugoptimized
if [[ $# -ge 1 ]]; then
	buildtype="$1"
fi

temp_dir=$(mktemp -d)
trap 'rm -rf "${temp_dir}"' EXIT

source_dir=$(pwd)
build_dir="${temp_dir}/build"
install_dir="${temp_dir}/install"

custom_sitelibs=$(scripts/print-python-libpath "${install_dir}")
export PYTHONPATH="${custom_sitelibs}${PYTHONPATH:+:${PYTHONPATH}}"
export LD_LIBRARY_PATH="${install_dir}/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
export PATH="${install_dir}/bin${PATH:+:${PATH}}"
export PKG_CONFIG_PATH="${install_dir}/lib/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}"

meson_args=(
	-Dprefix="${install_dir}"
	-Db_ndebug=if-release
	-Dbuildtype="${buildtype}"
	-Dc_args='-march=native -mtune=native'
	-Dcpp_args='-march=native -mtune=native'
)

cd "${temp_dir}"
curl -LJO https://github.com/fgrsnau/libqpbo/archive/v1.4.1.tar.gz
tar -xf libqpbo-1.4.1.tar.gz

mkdir "${build_dir}"
cd "${build_dir}"
meson setup "${meson_args[@]}" ../libqpbo-1.4.1
ninja install

find "${build_dir}" -mindepth 1 -delete

meson setup "${meson_args[@]}" -Dqpbo=enabled -Dgurobi=auto "${source_dir}"

ninja
ninja install

${SHELL}
