#!/bin/bash
set -eu -o pipefail

if [[ $# -ge 1 ]]; then
	buildarg=(--build-arg BUILDTYPE="$1")
else
	buildarg=()
fi

podman build "${buildarg[@]}" -f Containerfile.base -t libmpopt_base
podman build "${buildarg[@]}" -f Containerfile      -t libmpopt
podman run --privileged --rm -ti libmpopt
