#!/bin/bash
set -eu -o pipefail

LIBQPBO_VERSION=1.4.1

buildtype=debugoptimized
if [[ $# -ge 1 ]]; then
	buildtype="$1"
fi

temp_dir=$(mktemp -d)
trap 'rm -rf "${temp_dir}"' EXIT

source_dir=$(pwd)
prefix="${temp_dir}/install"

custom_sitelibs=$(scripts/print-python-libpath "${prefix}")
export PYTHONPATH="${custom_sitelibs}${PYTHONPATH:+:${PYTHONPATH}}"
export LD_LIBRARY_PATH="${prefix}/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
export PATH="${prefix}/bin${PATH:+:${PATH}}"

meson_args=(
	--prefix="${prefix}"
	--bindir=bin
	--libdir=lib
	--pkg-config-path="${prefix}/lib/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}"
	-Db_ndebug=if-release
	-Dbuildtype="${buildtype}"
	-Dc_args='-march=native -mtune=native'
	-Dcpp_args='-march=native -mtune=native'
)

cd "${temp_dir}"
curl -LJO "https://github.com/fgrsnau/libqpbo/archive/v${LIBQPBO_VERSION}.tar.gz"
tar -xf "libqpbo-${LIBQPBO_VERSION}.tar.gz"

mkdir libqpbo-build
cd libqpbo-build
meson setup "${meson_args[@]}" "../libqpbo-${LIBQPBO_VERSION}"
ninja install

cd "${temp_dir}"
mkdir libmpopt-build
cd libmpopt-build
meson setup "${meson_args[@]}" -Dqpbo=enabled -Dgurobi=auto "${source_dir}"
ninja install

${SHELL}
